### ISSUE TITLE
AssertionError when calling quiz.Schema.from_url()

### ISSUE THREAD

**Issue by markplindsay** [ariebovenberg/quiz#100]
Hi! I was excited to discover `quiz` because all of the other GraphQL client libs I encountered were not great.

I'm trying to use it with [Segment's GDPR API](https://segment.com/docs/guides/best-practices/user-deletion-and-suppression/#regulate-user-from-all-sources-in-workspace). However, I am receiving an unexpected `AssertionError` when I run `quiz.Schema.from_url` and pass in the API's URL. I am using `quiz==0.1.3`.

This code:
```python
import quiz

schema = quiz.Schema.from_url('https://gdpr.segment.com/graphql')
```

results in

```python
Traceback (most recent call last):
  File "/home/vagrant/app/venv/bin/suppress-and-delete", line 11, in <module>
    load_entry_point('app', 'console_scripts', 'suppress-and-delete')()
  File "/home/vagrant/app/app/scripts/suppress_and_delete.py", line 165, in main
    run_suppress_and_delete()
  File "/home/vagrant/app/app/scripts/suppress_and_delete.py", line 148, in run_suppress_and_delete
    segment.suppress_and_delete(49563)
  File "/home/vagrant/app/app/lib/segment.py", line 19, in suppress_and_delete
    schema = quiz.Schema.from_url('https://gdpr.segment.com/graphql')
  File "/home/vagrant/app/venv/local/lib/python2.7/site-packages/quiz/schema.py", line 345, in from_url
    return cls.from_raw(result['__schema'], scalars=scalars, module=module)
  File "/home/vagrant/app/venv/local/lib/python2.7/site-packages/quiz/schema.py", line 286, in from_raw
    by_kind[Union]
  File "/home/vagrant/app/venv/local/lib/python2.7/site-packages/quiz/schema.py", line 29, in _namedict
    return {c.__name__: c for c in classes}
  File "/home/vagrant/app/venv/local/lib/python2.7/site-packages/quiz/schema.py", line 29, in <dictcomp>
    return {c.__name__: c for c in classes}
  File "/home/vagrant/app/venv/local/lib/python2.7/site-packages/quiz/schema.py", line 65, in union_as_type
    assert len(typ.types) > 1
AssertionError
```

I expected this call to not result in an `AssertionError`, since the schema can be fetched successfully with e.g. https://github.com/prisma/get-graphql-schema:

```bash
$ get-graphql-schema https://gdpr.segment.com/graphql
schema {
  query: RootQuery
  mutation: RootMutation
}
...
```

Let me know if I can provide any more info. Thanks in advance for any help you can provide.

**Comment by ariebovenberg** [comment]
Hi @markplindsay, thanks for creating this issue. It looks like I wanted a sanity check for zero-length unions but typed `>` instead of `>=`. Fix should be out soon

**Comment by ariebovenberg** [comment]
release 0.1.4 is out with this fix. closed.

**Comment by markplindsay** [comment]
Thank you very much, @ariebovenberg, `quiz==0.1.4` works perfectly.

**Comment by ariebovenberg** [comment]
@markplindsay great news, let me know if you encounter any further issues
