### ISSUE TITLE
Error when importing quiz - There is no current event loop in thread

### ISSUE THREAD

**Issue by richin13** [ariebovenberg/quiz#230]
I'm currently trying to integrate `quiz` in my Flask application (tl;dr: I'll proxy one of my requests to a different Graphql API). When importing `quiz` (`import quiz`) I immediatly get a `RuntimeError` (the full stack trace is attached).
I'm not using any async capabilities of this library, is there a way to opt-out from async stuff?

It is worth mentioning that I'm running the flask application inside a docker container, and there are other containers running as well (some of them are also flask apps)

**Meta**

- Python version: 3.7.4
- Quiz version: `0.1.6`
- Flask version: `1.1.1`

**Stack trace**

```
Traceback (most recent call last):
  File "/home/kip/src/.venv/lib/python3.7/site-packages/flask/cli.py", line 83, in find_best_app
    app = call_factory(script_info, app_factory)
  File "/home/kip/src/.venv/lib/python3.7/site-packages/flask/cli.py", line 119, in call_factory
    return app_factory()
  File "/home/kip/src/app/__init__.py", line 31, in create_app
    register_blueprints(app_)
  File "/home/kip/src/app/__init__.py", line 49, in register_blueprints
    from app.views import FACEBOOK_BP, MISC_BP
  File "/home/kip/src/app/views/__init__.py", line 2, in <module>
    from .facebook import FACEBOOK_BP
  File "/home/kip/src/app/views/facebook.py", line 2, in <module>
    from app.graphql.schema import SCHEMA
  File "/home/kip/src/app/graphql/schema.py", line 4, in <module>
    from app.graphql.queries import Query
  File "/home/kip/src/app/graphql/queries/__init__.py", line 9, in <module>
    from app.providers.advertisers import KipCreateAdvertisersProvider
  File "/home/kip/src/app/providers/advertisers.py", line 5, in <module>
    import quiz
  File "/home/kip/src/.venv/lib/python3.7/site-packages/quiz/__init__.py", line 11, in <module>
    from .execution import *  # noqa
  File "/home/kip/src/.venv/lib/python3.7/site-packages/quiz/execution.py", line 6, in <module>
    import snug
  File "/home/kip/src/.venv/lib/python3.7/site-packages/snug/__init__.py", line 8, in <module>
    from . import clients, http  # noqa
  File "/home/kip/src/.venv/lib/python3.7/site-packages/snug/clients.py", line 2, in <module>
    from .compat import (set_urllib_method, singledispatch, urlencode,
  File "/home/kip/src/.venv/lib/python3.7/site-packages/snug/compat.py", line 10, in <module>
    event_loop = __import__('asyncio').get_event_loop()
  File "/usr/local/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-13'.
```

**Relevant code**

`app/__init__.py`

```python
import quiz  # << Fails here!


def create_app(config_overrides: Optional[Dict[str, Any]] = None) -> Flask:
    ...
```

**Comment by ariebovenberg** [comment]
Hi there, thanks for opening this issue. I'll have a look

**Comment by ariebovenberg** [comment]
I've found the cause if the issue, and will roll out a fix soon

**Comment by ariebovenberg** [comment]
Until I've rolled out a fix for `quiz`, you can force `snug==2.0.0` in your requirements

**Comment by richin13** [comment]
Thank you @ariebovenberg !

**Comment by richin13** [comment]
> Until I've rolled out a fix for quiz, you can force snug==2.0.0 in your requirements. This should solve the issue.

I don't see a `2.0.0` version, though. Did you mean `1.0.0`?

**Comment by richin13** [comment]
I tried using `snug==2.0.0` but the issue was still there. The current workaround I found was to use the following:

```python
try:
    import quiz
except RuntimeError:
    import asyncio

    asyncio.set_event_loop(asyncio.new_event_loop())
    import quiz
```

**Comment by ariebovenberg** [comment]
@richin13 does release `0.2.0` fix the issue? If not, could you post the traceback again? It should at least be different ;)

**Comment by richin13** [comment]
@ariebovenberg it's fixed now! Probably it was just some cache issue since I'm running the app inside a docker container.
Thank you very much for the quick fix!
